# Generated by Django 4.0.5 on 2022-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_status_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='text',
        ),
        migrations.AddField(
            model_name='todolist',
            name='summary',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст'),
        ),
    ]
