# Generated by Django 4.0.5 on 2022-06-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_to_do_list_date_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='date_of_completion',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Время выполнения'),
        ),
    ]
