# Generated by Django 4.0.5 on 2022-07-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_todolist_text_todolist_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='type',
        ),
        migrations.AddField(
            model_name='todolist',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='type_tasks', through='webapp.ToDoListType', to='webapp.type'),
        ),
        migrations.AddField(
            model_name='todolisttype',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='webapp.todolist', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='todolisttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_task', to='webapp.type', verbose_name='Тип'),
        ),
    ]
