# Generated by Django 4.0.5 on 2022-06-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_to_do_list_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='date_of_completion',
            field=models.DateField(blank=True, max_length=12, null=True, verbose_name='Время выполнения'),
        ),
    ]
