# Generated by Django 4.0.5 on 2022-07-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_todolisttype_remove_todolist_type_todolist_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='types',
            new_name='types_old',
        ),
    ]
