# Generated by Django 4.0.5 on 2022-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_to_do_list_date_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
