# Generated by Django 4.0.5 on 2022-06-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_to_do_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='update',
            field=models.DateField(auto_now=True, max_length=12, verbose_name='Время изменения'),
        ),
    ]
