# Generated by Django 4.0.5 on 2022-07-12 06:06

from django.db import migrations


def transfer_tags(apps, schema_editor):
    ToDolist = apps.get_model('webapp.ToDolist')

    for task in ToDolist.objects.all():
        task.types.set(task.types_old.all())


def rollback_transfer(apps, schema_editor):
    ToDolist = apps.get_model('webapp.ToDolist')

    for task in ToDolist.objects.all():
        task.types_old.set(task.tags.all())


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0006_todolist_types_alter_todolist_types_old'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
