# Generated by Django 4.0.5 on 2022-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_to_do_list_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='update',
            field=models.DateField(auto_now_add=True, max_length=12, null=True, verbose_name='Время изменения'),
        ),
    ]
