# Generated by Django 4.0.5 on 2022-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_to_do_list_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='update',
            field=models.DateField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
    ]
