# Generated by Django 4.0.5 on 2022-07-19 06:59

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_todolist_types_old_delete_todolisttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='summary',
            field=models.CharField(max_length=100, null=True, validators=[webapp.validate.MinLengthValidator(15)], verbose_name='Описание'),
        ),
    ]
