# Generated by Django 4.0.5 on 2022-07-26 08:59

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_todolist_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_begin', models.DateField(max_length=20, verbose_name='Дата начала')),
                ('data_end', models.DateField(blank=True, max_length=20, null=True, verbose_name='Дата Окончания')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='todolist',
            name='summary',
            field=models.CharField(max_length=15, null=True, validators=[webapp.validate.MinLengthValidator(15)], verbose_name='Описание'),
        ),
    ]
