# Generated by Django 4.0.5 on 2022-07-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_project_alter_todolist_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='webapp.project', verbose_name='Проект'),
        ),
    ]
